### ISSUE TITLE
How do I force a form-feed after printing 60 lines?

### ISSUE THREAD

**Issue by rwmills** [pascalgp/elp2pdf#2]
I am running elp2pdf with the _--lptype mpev_ switch set.

If I run a program that generates a form-feed after outputting 60 lines everything looks perfect.

The problem is that some of the programs I am using **do not** generate any form-feeds but expects the printer to do it. I have sent you a small (5 page) example. P.S. is there a way to drop the creation of the blank page at the end?

First I have to say that although I have been programming for 47 years (retired in 2012), and am quite conversant in 11+ different languages. I have never used Perl and think my brain might complain if I try to load another one.

With that said, I've had a look at the code and within elp-mpev.pl I see the number 66 appearing a lot of times in check_read and check_print. Changing them from 66 to 60 did not give me the results I was looking for. I think that a lack of understanding of their relationship with the other numbers in the **if** statements didn't help.

I have also been looking at the code in elp2pdf.pl with the intention of adding a _--Media_ | _-m_ switch so that the _-M_ switch passed to enscript is no longer hard-coded. I'd also like to include the _--system-id_ | _-s_ and _--name_ | _-n_ values in the PDF header and PDF filename. But those are things to be done at a later time

[S1_O3_OPERATOR.SYS_QUADLIST_NOV_17_2025_02_33_PM.pdf](https://github.com/user-attachments/files/23592141/S1_O3_OPERATOR.SYS_QUADLIST_NOV_17_2025_02_33_PM.pdf)

.

**Comment by pascalgp** [comment]
I'm not very familiar with MPE. I worked on it briefly over 25 years ago. I know how to print a file the following way, which generates a form feed every 60th line:

file printer;dev=lp
fcopy from=<filespec>;to=*printer

Do you know of commands I can use on the base MPE/V distribution to generate printer output without automatic form feeds?

The elp2pdf utility would benefit from an enhancement allowing print form specifications but short of that, I could come up with a workaround.

**Comment by rwmills** [comment]
> Do you know of commands I can use on the base MPE/V distribution to generate printer output without automatic form feeds?

If you put a filename between 'from=' and ';to=' (eg. fcopy from=filename;to=*printer) then your fcopy statement from above will do what you want. Fcopy knows nothing about the device it is sending the file to. The spooler process for the device only has limited knowledge about it. As far as it is concerned a form-feed code is just data. It is the software within the printer itself that actions the form-feed code and does a page throw.

There is another program that you can use to test this. It is the text file editor for MPE/V.

file listfile;dev=lp
editor *listfile
/text filename
/list all,offline
/exit

The reason the printed file starts on a new page is because the spooler process sends a form-feed code to the printer after it has sent the start banner page. It also sends a form-feed before it sends the end banner page.

**Comment by pascalgp** [comment]
I started the printer with this command:

~/printer/elp2pdf.pl -l mpev -t -s MPE -P ~/printout -f Courier10 -k 2 -h 3 lp.out

Then printed a file using these commands you provided:

file listfile;dev=lp
editor *listfile
text MD467A.HP32340.SUPPORT
list all,offline

Also printed at the MPE command line:

file printer;dev=lp
fcopy from=MD467A.HP32340.SUPPORT;to=*printer

I get the files attached which I believe are formatted the way you want:

[S1_O2_OPERATOR.SYS_LISTFILE_NOV_23_1997_04_14_AM.pdf](https://github.com/user-attachments/files/23699228/S1_O2_OPERATOR.SYS_LISTFILE_NOV_23_1997_04_14_AM.pdf)

[S1_O3_OPERATOR.SYS_PRINTER_NOV_23_1997_04_20_AM.pdf](https://github.com/user-attachments/files/23699229/S1_O3_OPERATOR.SYS_PRINTER_NOV_23_1997_04_20_AM.pdf)

The printer output is:

Nov 23 14:14:34 MPE printer started
Nov 23 14:15:12 MPE reading
Nov 23 14:15:12 MPE processing 918 lines
Nov 23 14:15:12 MPE file S1_O2_OPERATOR.SYS_LISTFILE_NOV_23_1997_04_14_AM.pdf
Nov 23 14:15:12 MPE done
Nov 23 14:20:37 MPE reading
Nov 23 14:20:37 MPE processing 852 lines
Nov 23 14:20:37 MPE file S1_O3_OPERATOR.SYS_PRINTER_NOV_23_1997_04_20_AM.pdf
Nov 23 14:20:38 MPE done

It looks like the behavior is different in your environment. Some info about my platform:

Ubuntu 22.04.5 LTS
Perl v5.34.0
GNU Enscript 1.6.5.90
GPL Ghostscript 9.55.0 (2021-09-27)

Edit: This printer command gives the proper font pitch but results are the same when it comes to formatting.

 .~/printer/elp2pdf.pl -l mpev -t -s MPE -P ~/printout  -h 3 lp.out

**Comment by rwmills** [comment]
My platform is Linux Mint 21.3 with the same versions of Perl, Enscript and Ghostscript.

I am assuming that you are using David Bryan's release of the HP3000 Series 58 Simulator which only has a single ADCC and the LP printer goes to a file.

I am using Gavin Scott's Turnkey Simulator which has several ADCC's and LDEV 11 is configured as a Serial Printer and sends it output to TCP Port 1043.

There are 3 differences between the parameters I pass to elp2pdf.pl and what you pass.

- I left the -k switch default to 0 as there was no explanation on what the switch was used for. You set it to 2.
- I left the -f switch default to Courier12 as that was an acceptable size. You set it to Courier10.
- I use the -i and -p switches. You use the -t switch and pass it a file.

I added the -k switch with a value of 2 and ran it. I have attached the results.

I then changed the -f switch to Courier10 and ran it again. Apart from the font being a bit to small for me and the extra blank page at the end it looks fine. I have attached the results.

If I could end up with the second run with the larger font size then I would say the result was perfect (for me).

Thanks for your quick response and help.

[S1_O2_OPERATOR.SYS_LISTFILE_NOV_23_2025_11_31_PM.pdf](https://github.com/user-attachments/files/23699701/S1_O2_OPERATOR.SYS_LISTFILE_NOV_23_2025_11_31_PM.pdf)

[S1_O2_OPERATOR.SYS_LISTFILE_NOV_23_2025_11_49_PM.pdf](https://github.com/user-attachments/files/23699704/S1_O2_OPERATOR.SYS_LISTFILE_NOV_23_2025_11_49_PM.pdf)

**Comment by pascalgp** [comment]
The k switch introduces extra space between lines. Try:

-f Courier12
-k 0

Courier12 doesn't need the extra vertical spacing that Courier10 does.

Here's a sample of what I get:

[S1_O3_OPERATOR.SYS_PRINTER_NOV_23_1997_06_16_AM.pdf](https://github.com/user-attachments/files/23699814/S1_O3_OPERATOR.SYS_PRINTER_NOV_23_1997_06_16_AM.pdf)

As for the extra blank page, that should be easy to fix. I would need to be able to test but as you point out, we're using different emulators.

**Comment by rwmills** [comment]
I need to give you an apology as EDITOR does not format its offline listings the way I thought it did. It inserts page header lines unlike FCOPY and QUAD which don't.

My excuse is that prior to yesterday I had not used EDITOR since the early 1980's. After then I had mainly used QEDIT and QUAD for editing source code. When the company was unwilling to pay for QEDIT I would install the latest version of QUAD from the HP3000 Contributed Software Library (it is free). QUAD does not add page heading lines to its offline listings.

**elp2pdf.pl**

In $usage you have **--baselineskip** instead of **--skip** which is used in the GetOptions function.

**Comment by pascalgp** [comment]
"In $usage you have --baselineskip instead of --skip which is used in the GetOptions function."

Fixed. Thank you for spotting that.

**Comment by rwmills** [comment]
You forgot to also update the README.md file (the usage and the paragraph above it).

**Comment by pascalgp** [comment]
Corrected. Thanks again!
